services:

  mandalorian:
    build: dnsserver
    hostname: mandalorian
    command: -g -4
    volumes:
      - ./mandalorian/named.conf.options:/etc/bind/named.conf.options
      - ./mandalorian/named.conf:/etc/bind/named.conf

    networks:
      rededns:
        ipv4_address: 192.168.20.9

  darthvader:
    build: dnsserver
    hostname: darthvader
    command: -g -4
    volumes:
      - ./darthvader/named.conf.local:/etc/bind/named.conf.local

    networks:
      rededns:
        ipv4_address: 192.168.20.10

    
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 192.168.20.110

    dns: 
    - 192.168.20.10

networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24


